language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules
env:
    - CI=true
script:
    - yarn global add lerna
    - yarn run build-storybook
    - lerna publish --yes
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token # Set in the settings page of your repository, as a secure variable
    local_dir: storybook-static
    on:
      branch: feature-lerna
deploy:
  provider: npm
  email: "5541037@qq.com"
  api_key: $npm_token
  on:
    branch: feature-lerna