language: node_js
node_js:
    - '14.17'
cache:
    yarn: true
    directories:
        - node_modules
env:
    - CI=true
script:
    - yarn run build-storybook
# deploy:
#     provider: pages
#     skip_cleanup: true
#     github_token: $github_token # Set in the settings page of your repository, as a secure variable
#     local_dir: storybook-static
#     on:
#         branch: feature-lerna
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
    - yarn run lerna run prepublishOnly
before_deploy:
    - echo `//registry.npmjs.org/:_authToken=\${$AUTH_TOKEN}` >> $HOME/.npmrc 2> /dev/null

deploy:
    # provider: npm
    # email: "$NPM_EMAIL"
    # api_key: "$NPM_TOKEN"
    # skip_cleanup: true
    # on:
    #     branch: feature-lerna
    provider: script
    script: 'yarn run lerna:publish'
    skip_cleanup: true
    on:
        branch: feature-lerna
    # provider: pages
    # skip_cleanup: true
    # github_token: $github_token # Set in the settings page of your repository, as a secure variable
    # local_dir: storybook-static
    # on:
    #     branch: feature-lerna
