export { default as IconEdit } from './IconEdit'
// export { default as IconArrow } from './IconArrow'
// export { default as IconPlus } from './IconPlus'
// export { default as IconCube } from './IconCube'
// export { default as IconGuide } from './IconGuide'
// export { default as IconMoney } from './IconMoney'
// export { default as IconCommission } from './IconCommission'
// export { default as IconClose } from './IconClose'
// export { default as IconConfirm } from './IconConfirm'
// export { default as IconTime } from './IconTime'
// export { default as IconHelp } from './IconHelp'
// export { default as IconGalaxy } from './IconGalaxy'
// export { default as IconWarning } from './IconWarning'
// export { default as IconTick } from './IconTick'
// export { default as IconLoading } from './IconLoading'
// export { default as IconF } from './IconF'
// export { default as IconRadioCheck } from './IconRadioCheck'
// export { default as IconRadioUncheck } from './IconRadioUncheck'
